name: Run Unit and Cypress Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  UnitTests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: NPM Clean Install
        run: npm ci
      - name: Execute Unit tests
        run: npm run test
      - name: Execute Typechecking
        run: npm run type-check

  Run-Cypress-Tests:
    needs: [ UnitTests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run cypress:ci
          working-directory: ./playground
